load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_python",
    sha256 = "4912ced70dc1a2a8e4b86cec233b192ca053e82bc72d877b98e126156e8f228d",
    strip_prefix = "rules_python-0.32.2",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.32.2/rules_python-0.32.2.tar.gz",
)

load("@rules_python//python:repositories.bzl", "py_repositories", "python_register_multi_toolchains")

py_repositories()

python_versions = [
    "3.12",
    "3.11",
    "3.10",
    "3.9",
    "3.8",
]

python_register_multi_toolchains(
    name = "python",
    default_version = python_versions[0],
    python_versions = python_versions,
    register_coverage_tool = True,
)

local_repository(
    name = "rules_ophiuchus",
    path = "../..",
)

load("@rules_ophiuchus//python:poetry_parse.bzl", "poetry_parse")
load("@rules_ophiuchus//python:repositories.bzl", install_poetry_dependencies = "install_dependencies")

install_poetry_dependencies()

poetry_parse(
    name = "poetry_repo1",
    lock = "//:poetry.lock",
)

poetry_parse(
    name = "poetry_repo2",
    lock = "//:poetry.lock",
)
