default_install_hook_types:
  - pre-commit
  - pre-push

default_stages:
  - pre-commit

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.3
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format

  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: v2.6.0
    hooks:
      - id: pyproject-fmt

  - repo: local
    hooks:
      - id: check-version
        name: check Commit Messages
        stages: [pre-commit]
        require_serial: true
        language: script
        entry: ./tools/check_version.py
