load("@ofiuco_defs//:defs.bzl", _python_host = "python_host")

def _parse_lock_impl(rctx):
    self = str(rctx.path(rctx.attr._self)).split("/external/")[-1]
    header = "# Autogenerated file by _parse_lock_impl in {}".format(self)
    header += '''\n\nload("@rules_python//python:py_library.bzl", "py_library")'''
    rules_repository = self.split("/", 1)[0]
    rules_repository = ("@@" if "~" in rules_repository else "@") + rules_repository
    rules_repository = rules_repository.split("+")[0]
    prefix = '''{header}\n\nload("{name}//python/private:poetry_deps.bzl", "package")'''.format(header = header, name = rules_repository)

    interpreter = rctx.path(rctx.attr._python_host)
    exec_result = rctx.execute([
        interpreter,
        rctx.path(rctx.attr._lock_parser),
        rctx.path(rctx.attr.lock),
        json.encode(rctx.attr.platforms),
        "--{}generate_extras".format("" if rctx.attr.generate_extras else "no"),
        "--project_file={}".format(rctx.path(rctx.attr.toml) if rctx.attr.toml else ""),
    ])
    if exec_result.return_code:
        fail("Parsing {} failed with exit code {}\n{}\n".format(rctx.attr.lock, exec_result.return_code, exec_result.stderr))

    rctx.file("BUILD.bazel", "{}\n\n{}".format(prefix, exec_result.stdout))
    rctx.file("WORKSPACE")

parse_lock = repository_rule(
    attrs = {
        "lock": attr.label(
            allow_single_file = True,
            doc = "Poetry lock file",
        ),
        "toml": attr.label(
            allow_single_file = True,
            doc = "pyproject file",
        ),
        "generate_extras": attr.bool(
            default = True,
            doc = "Generate packages with extra dependencies",
        ),
        "platforms": attr.string_dict(
            doc = "The mapping of interpter substrings to Python platform tags and environment markers as a JSON string",
        ),
        "_lock_parser": attr.label(
            allow_single_file = True,
            default = ":lock_parser.py",
        ),
        "_python_host": attr.label(
            allow_single_file = True,
            default = _python_host,
        ),
        "_self": attr.label(
            allow_single_file = True,
            default = ":lock_parser.bzl",
        ),
    },
    doc = """Process Poetry lock file.""",
    implementation = _parse_lock_impl,
)
