load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "rules_python",
    sha256 = "e3f1cc7a04d9b09635afb3130731ed82b5f58eadc8233d4efb59944d92ffc06f",
    strip_prefix = "rules_python-0.33.2",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.33.2/rules_python-0.33.2.tar.gz",
)

load("@rules_python//python:repositories.bzl", "py_repositories", "python_register_multi_toolchains")

py_repositories()

python_versions = [
    "3.12",
    "3.11",
    "3.10",
    "3.9",
    "3.8",
]

python_register_multi_toolchains(
    name = "copperhead",
    default_version = python_versions[0],
    python_versions = python_versions,
    register_coverage_tool = True,
)

local_repository(
    name = "ofiuco",
    path = "../..",
)

load("@ofiuco//python:repositories.bzl", install_poetry_dependencies = "install_dependencies")

install_poetry_dependencies("copperhead_3_11", "3.11")

load("@ofiuco//python:poetry_parse.bzl", "poetry_parse")

poetry_parse(
    name = "poetry_repo1",
    lock = "//:poetry.lock",
)

poetry_parse(
    name = "poetry_repo2",
    lock = "//:poetry.lock",
)
