load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# https://github.com/bazelbuild/rules_python/releases/tag/1.0.0
http_archive(
    name = "rules_python",
    sha256 = "4f7e2aa1eb9aa722d96498f5ef514f426c1f55161c3c9ae628c857a7128ceb07",
    strip_prefix = "rules_python-1.0.0",
    url = "https://github.com/bazelbuild/rules_python/releases/download/1.0.0/rules_python-1.0.0.tar.gz",
)

load("@rules_python//python:repositories.bzl", "py_repositories", "python_register_multi_toolchains")

py_repositories()

python_versions = [
    "3.13",
    "3.12",
    "3.11",
    "3.10",
    "3.9",
]

python_register_multi_toolchains(
    name = "copperhead",
    default_version = python_versions[0],
    python_versions = python_versions,
    register_coverage_tool = True,
)

local_repository(
    name = "ofiuco",
    path = "../..",
)

load("@ofiuco//python:repositories.bzl", install_poetry_dependencies = "install_dependencies")

install_poetry_dependencies("@copperhead_3_13_host//:python", "3.13")

load("@ofiuco//python:lock_parser.bzl", "parse_lock")

parse_lock(
    name = "poetry_repo1",
    lock = "//:poetry.lock",
)

parse_lock(
    name = "poetry_repo2",
    lock = "//:poetry.lock",
)
