[build-system]
build-backend = "hatchling.build"

requires = [ "hatchling" ]

[project]
name = "sample-package-hatchling"
version = "1.2.3"
description = "Sample package"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
]
dependencies = [  ]

[tool.hatch.build.targets.wheel]
packages = [ "sample_package_hatchling" ]
